export const ADD_QUESTION = "ADD_QUESTION";
export const CHANGE_QUESTION = "CHANGE_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const DELETE_QUESTIONS_BY_QUIZ_ID = "DELETE_QUESTIONS_BY_QUIZ_ID";
